/* CREATING TABLES WITHOUT FOREIGN KEYS*/
CREATE TABLE Spring25_S003_T7_STUDENT (
    MAV_ID     NUMBER(10) PRIMARY KEY,
    FIRST_NAME VARCHAR2(50),
    LAST_NAME  VARCHAR2(50),
    DATE_OF_BIRTH  DATE
);

CREATE TABLE Spring25_S003_T7_RESTAURANT (
    REST_ID NUMBER(10) PRIMARY KEY,
    NAME VARCHAR2(50),
    PH_NO  NUMBER(10),
    RATING NUMBER CONSTRAINT rating_range_check CHECK (rating >= 0 AND rating <= 5),
    STREET VARCHAR2(25),
    APT VARCHAR2(25),
    CITY VARCHAR2(25),
    ZIPCODE NUMBER(5)    
);

CREATE TABLE Spring25_S003_T7_CSA (
    AGENT_ID NUMBER(10) PRIMARY KEY,
    FIRST_NAME VARCHAR2(50),
    LAST_NAME  VARCHAR2(50),
    DATE_OF_BIRTH  DATE
);

CREATE TABLE Spring25_S003_T7_PROMOCODE (
    CODE VARCHAR2(6) PRIMARY KEY,
    AMOUNT_SAVED NUMBER(3),
    EXPIRY_DATE  DATE
);

CREATE TABLE Spring25_S003_T7_DELIVERY_AGENT (
    ID NUMBER(10) PRIMARY KEY,
    FIRST_NAME VARCHAR2(50),
    LAST_NAME  VARCHAR2(50),
    DATE_OF_BIRTH  DATE,
    PHONE_NO NUMBER(10),
    SSN NUMBER(9),
    INSURANCE_NO NUMBER(11),
    PROVIDER_NAME VARCHAR2(15),
    COVERAGE_TIME NUMBER(2),
    COVERAGE_AMT NUMBER(5)
);

/*CREATING TABLES WITH FOREIGN KEYS*/
CREATE TABLE Spring25_S003_T7_STUDENT_PHONENO (
    MAV_ID    NUMBER(10),
    PHONE_NO  NUMBER(10),
    CONSTRAINT pk_student_phoneno PRIMARY KEY (MAV_ID, PHONE_NO),
    CONSTRAINT fk_student_phoneno FOREIGN KEY (MAV_ID)REFERENCES Spring25_S003_T7_STUDENT (MAV_ID)
);

CREATE TABLE Spring25_S003_T7_STUDENT_ADDRESS (
    MAV_ID    NUMBER(10),
    STREET VARCHAR2(25),
    APT VARCHAR2(25),
    CITY VARCHAR2(25),
    ZIPCODE NUMBER(5),
    CONSTRAINT pk_student_student_address PRIMARY KEY (MAV_ID,STREET,APT,CITY,ZIPCODE),
    CONSTRAINT fk_student_student_address FOREIGN KEY (MAV_ID)REFERENCES Spring25_S003_T7_STUDENT (MAV_ID)
);

CREATE TABLE Spring25_S003_T7_CSA_SHIFT_TIMING (
    AGENT_ID NUMBER(10),
    SHIFT_TIMING DATE,
    CONSTRAINT pk_csa_shift_timing PRIMARY KEY (AGENT_ID,SHIFT_TIMING),
    CONSTRAINT fk_csa_shift_timing FOREIGN KEY (AGENT_ID) REFERENCES Spring25_S003_T7_CSA(AGENT_ID)
);

CREATE TABLE Spring25_S003_T7_ORDERS (
    ORDER_ID NUMBER(10) PRIMARY KEY,
    TOTAL_AMT NUMBER(4),
    MAV_ID NUMBER(10),
    REST_ID NUMBER(10),
    DELIVERY_AGENT_ID NUMBER(10),
    ORDER_DATE DATE,
    ORDER_TIME VARCHAR2(9),
    PICKUP_TIME VARCHAR2(9),
    CONSTRAINT fk_orders_mavid FOREIGN KEY (MAV_ID) REFERENCES Spring25_S003_T7_STUDENT(MAV_ID),
    CONSTRAINT fk_orders_restid FOREIGN KEY (REST_ID) REFERENCES Spring25_S003_T7_RESTAURANT(REST_ID),
    CONSTRAINT fk_orders_dagent FOREIGN KEY (DELIVERY_AGENT_ID) REFERENCES Spring25_S003_T7_DELIVERY_AGENT(ID)
);

CREATE TABLE Spring25_S003_T7_MENU (
    DISH_ID NUMBER(10),
    REST_ID NUMBER(10),
    DISH_NAME VARCHAR2(25),
    CUISINE VARCHAR2(20),
    PRICE NUMBER(3),
    CONSTRAINT pk_menu PRIMARY KEY (REST_ID,DISH_ID),
    CONSTRAINT fk_menu FOREIGN KEY (REST_ID) REFERENCES Spring25_S003_T7_RESTAURANT(REST_ID)
);

CREATE TABLE Spring25_S003_T7_ORDER_ITEMS (
    ORDER_ID NUMBER(10),
    ITEM VARCHAR2(25),
    CONSTRAINT pk_order_items PRIMARY KEY (ORDER_ID,ITEM),
    CONSTRAINT fk_order_items FOREIGN KEY (ORDER_ID) REFERENCES Spring25_S003_T7_ORDERS(ORDER_ID)
);

CREATE TABLE Spring25_S003_T7_RATES (
    DELIVERY_AGENT_ID NUMBER(10),
    MAV_ID NUMBER(10),
    RATING NUMBER CONSTRAINT rating_range_check_2 CHECK (rating >= 0 AND rating <= 5),
    DROP_OFF_TIME VARCHAR2(9),
    CONSTRAINT pk_rates PRIMARY KEY (DELIVERY_AGENT_ID,MAV_ID),
    CONSTRAINT fk_rates_deliveryagent FOREIGN KEY (DELIVERY_AGENT_ID) REFERENCES Spring25_S003_T7_DELIVERY_AGENT(ID),
    CONSTRAINT fk_rates_student FOREIGN KEY (MAV_ID) REFERENCES Spring25_S003_T7_STUDENT(MAV_ID)
);

CREATE TABLE Spring25_S003_T7_CALLS (
    AGENT_ID NUMBER(10),
    MAV_ID NUMBER(10),
    CALL_DATE DATE,
    CONSTRAINT pk_calls PRIMARY KEY (AGENT_ID,MAV_ID),
    CONSTRAINT fk_calls_csa FOREIGN KEY (AGENT_ID) REFERENCES Spring25_S003_T7_CSA(AGENT_ID),
    CONSTRAINT fk_calls_student FOREIGN KEY (MAV_ID) REFERENCES Spring25_S003_T7_STUDENT(MAV_ID)
);

CREATE TABLE Spring25_S003_T7_ADDPROMO (
    MAV_ID NUMBER(10),
    CODE VARCHAR2(6),
    USAGE_DATE DATE,
    CONSTRAINT pk_addpromo PRIMARY KEY (MAV_ID,CODE),
    CONSTRAINT fk_addpromo_promocode FOREIGN KEY (CODE) REFERENCES Spring25_S003_T7_PROMOCODE(CODE),
    CONSTRAINT fk_addpromo_student FOREIGN KEY (MAV_ID) REFERENCES Spring25_S003_T7_STUDENT(MAV_ID)
);
